url: https://shreyagokhe.github.io
baseurl: /portfolio/

# Site settings
title: Hello
email: sgokhe@stevens.edu
description: "Hi, welcome to my portfolio. Let's explore my journey!"

# Team names, titles and social links
people:
- name: Shreya Gokhe
  pic: 1
  position: Master's student at Stevens Institute Of Technology
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: http://www.linkedin.com/in/shreya-gokhe/
  - title: twitter
    url: http://twitter.com/ShreyaGokhe
  - title: github
    url:https://github.com/shreyagokhe

# Postal address (add as many lines as necessary)
address:
  - line: Jersey City, NJ 07307

# Build settings
markdown: kramdown
permalink: pretty
